name: Android CI

on:
  push:
    branches:
      - main
      - ci

  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      # 1. Download the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Give Gradle permission to execute
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # 4. Run all unit tests
      - name: Run Unit Tests
        run: ./gradlew test